-- DROPEAR PACKAGE 
DROP PACKAGE umc_itr_ax

-- TABLE AUX
CREATE TABLE MOD_COM (
	id NUMBER PRIMARY KEY NOT null,
	canal varchar(50),
	user_current varchar(50)
)

DROP TABLE MOD_COM 
-- 

-- CREAR NUEVO PACKAGE

-- DECLARACION
CREATE OR REPLACE PACKAGE ACSELX.UMC_TEST IS
-- Package header
	PROCEDURE INSERT_NUEVO (cID NUMBER
						);
END UMC_TEST;
-- FIN DECLARACION


-- BODY
CREATE OR REPLACE PACKAGE BODY ACSELX.UMC_TEST IS
-- Package body
	PROCEDURE INSERT_NUEVO (cID NUMBER) IS 
	-- SET serveroutput ON	
	usr_current varchar(50);
		BEGIN			
			select USER INTO usr_current from dual;
			INSERT INTO ACSELX.MOD_COM (ID, CANAL, USER_CURRENT) VALUES(cID, 'NUEVO', usr_current);
			EXCEPTION
			    WHEN DUP_VAL_ON_INDEX THEN
			    -- DBMS_OUTPUT.PUT_LINE('Duplicate value on index');
			    	UPDATE ACSELX.MOD_COM SET CANAL = 'NUEVOREPLACE', USER_CURRENT = usr_current WHERE ID = cID;
		END INSERT_NUEVO;
END UMC_TEST;
-- FIN BODY


-- EJECUTAR SP DENTRO DE UN PACKAGE
BEGIN 
	ACSELX.UMC_TEST.INSERT_NUEVO(ID => :cID); 
END;
-- FIN EJECUTAR SP DENTRO DE UN PACKAGE





